# Generated by Django 5.0.6 on 2025-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longititude', models.FloatField(verbose_name='Довгота')),
            ],
        ),
    ]
