# Generated by Django 5.0.6 on 2025-01-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='longititude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
    ]
