# Generated by Django 5.0.6 on 2025-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_service_servicetype_price_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='min_price',
        ),
        migrations.AddField(
            model_name='price',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
